### ISSUE TITLE
Failed to access local Storage on Devices with local Storage turned off

### ISSUE THREAD

**Issue by DanielHabenicht** [mobxjs/mobx-angular#67]
Using `"mobx-angular"` with `"version": "2.1.1"`. 

If localStorage is disabled (I have tested it with [Chrome](http://tips.tutorialhorizon.com/2016/08/18/deny-disable-localstorage-in-chrome/)) the following Error is thrown: 

`mobx-angular-debug.js:6 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at eval (webpack-internal:///../../../../mobx-angular/dist/utils/mobx-angular-debug.js:8:5)
    at eval (webpack-internal:///../../../../mobx-angular/dist/utils/mobx-angular-debug.js:257:3)
    at Object.../../../../mobx-angular/dist/utils/mobx-angular-debug.js (http://localhost:4200/vendor.bundle.js:406:1)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:30)
    at eval (webpack-internal:///../../../../mobx-angular/dist/directives/mobx-autorun.directive.js:5:84)
    at Object.../../../../mobx-angular/dist/directives/mobx-autorun.directive.js (http://localhost:4200/vendor.bundle.js:382:1)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:30)
    at eval (webpack-internal:///../../../../angular-tree-component/dist/components/tree-node-checkbox.component.ngfactory.js:10:10)
    at Object.../../../../angular-tree-component/dist/components/tree-node-checkbox.component.ngfactory.js (http://localhost:4200/vendor.bundle.js:55:1)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:55:30)`

The reason is that Access to local Storage is denied. There should be a `try{}catch{}` Function.

Note: I will provide a Pull Request shortly.

**Comment by Coletex** [comment]
Hi,
I'm also having this issue. Are there any news about the integration of the pull request?

**Comment by DanielHabenicht** [comment]
I don't know. Could not keep track of the file in the current repository

**Comment by adamkleingit** [comment]
Fixed in #68 thanks!
